### PR TITLE
dummy docker stuff

### PR DESCRIPTION
**Pull request by stenczelt**
this has been added in order to test what is going on on #5 and see what seemingly orthogonal change is not that in fact, or if the main branch is fragile

### CODE REVIEW

**Comment by stenczelt** [comment]
@jameskermode I am confused now. I have only added a no-action CI step here, what could be the problem?

**Comment by jameskermode** [comment]
Not sure. Will try to take a look when I'm back next week.

**Comment by stenczelt** [comment]
@jameskermode do you see any sifnificant changes in this? it looks like only trailing whitespace and an extra task that we are not even getting to

**Comment by jameskermode** [comment]
I agree these changes look innocuous. Not sure what's going on.

**Comment by jameskermode** [comment]
I suggest uncommenting the lines about ssh debugging, then you can connect to the worker node and see what's in the script that reports a bash syntax error.

**Comment by jameskermode** [comment]
Closing in preparation for archiving repo.

**Pull request closed without merging**
