### PR TITLE
docker build for minimal quippy image using PyPI install

### PR DESCRIPTION
**Pull request by stenczelt**
This is a copy of the one tested in `quip-docker` yesterday.

todo:
- [x] docker image
- [x] CI in github
- [ ] CI to depend on the PyPI release passing

### CODE REVIEW

**Comment by jameskermode** [comment]
Looks fine, but as you say not yet coupled to successful push to PyPI. You could add the Docker build as a task at the end of the main workflow, and reuse the logic that check the format of the tag:

https://github.com/libAtoms/quippy-wheels/blob/main/.github/workflows/build.yml#L103

**Comment by jameskermode** [comment]
(The final `-arm64` wheel will fail, but that's not related to this PR so I'll be happy to merge it anyway)

**Comment by stenczelt** [comment]
Hmmm. It looks like many of them have failed, and are hanging in the ssh session. I suppose we would be able to ssh into these now. Seemingly most of them have been hanging there for ~20 min now.

**Comment by jameskermode** [comment]
Probably I messed something up trying to get arm64 working. Don't worry about this for now, it's independent of your changes. I don't have time to look at this today but will get back to it before too long.

**Comment by stenczelt** [comment]
I have tested a couple of things now on how to run multiple steps, I think it would be generally better to keep these in two separate workflow files and use the events to trigger the docker build:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#status

what do you think?

**Comment by jameskermode** [comment]
sounds like a good idea to me

**Comment by stenczelt** [comment]
rebased onto the main, let's see if the build works not and then I can make the docker build depend on the PyPI push

**Comment by stenczelt** [comment]
@jameskermode why are the builds failing in the build and test stage? Can you take a look?

**Comment by jameskermode** [comment]
Sorry, I'm messing with the main branch right now to try to get the Apple arm64 build working. I should do that on a branch really. Leave this with me and I'll trigger a new build once I've finished, then I can merge this when it passes.

**Comment by stenczelt** [comment]
OK, let me know when you are ready with that and I will change the workflow in this one to be dependent on the success of those PyPI builds, then we can merge when that is all working

**Comment by jameskermode** [comment]
if you rebase on `main` now this should work for all platforms

**Pull request closed without merging**
